[tool.poetry]
name = "netown"
version = "0.1.0"
description = ""
authors = ["ashHQ"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scapy = "^2.6.1"
pywifi = "^1.1.12"
pexpect = "^4.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
